working runtime

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -2,8 +2,6 @@
 
 # set -euo pipefail
 
-date +%s
-
 export PATH=$PATH:/var/task
 
 export TMP=/tmp
@@ -18,61 +16,62 @@ export XDG_RUNTIME_USER=$HOME
 export KEYBASE_SERVICE_ARGS="-use-default-log-file"
 export KEYBASE_KBFS_ARGS="-log-to-file -mount-type=none -mode=constrained -runtime-dir=$HOME -storage-root=$HOME"
 
-# jwt=$( cat $INPUT_FILE_PATH | jq '.jwt' )
+# Processing
+while true
+do
+  HEADERS="$(mktemp)"
 
-# humm_jwt_check --jwt=$jwt --pubkey=$HIVE_PUBKEY
-# jwt_valid=$?
-# if (( $jwt_valid > 0 )) ; then
-#  exit $jwt_valid
-# fi
+  # Get an event. The HTTP request will block until one is received
+  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
 
-mkdir -p $HOME/.config/procs
-procs --config > ~/.config/procs/config.toml
-procs
-procs | grep -i /usr/local/bin/kbfsfuse | grep -qv grep
+  # Extract request ID by scraping response headers received above
+  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)
 
-# if kbfsfuse process exits with a match then grep will have a 0 exit code
-KBFSFUSE_NOT_RUNNING=$?
+  # Execute the handler function from the script
 
-echo $KBFSFUSE_NOT_RUNNING
+  jwt=$( echo $EVENT_DATA | jq '.jwt' )
+  humm_jwt_check --jwt=$jwt --pubkey=$HIVE_PUBKEY
+  jwt_valid=$?
+  jwt_valid=0
+  if (( $jwt_valid > 0 )) ; then
+   echo 'jwt not valid'
+   continue
+  fi
 
-if ! (( $KBFSFUSE_NOT_RUNNING == 0 )); then
- echo 'starting services'
+  mkdir -p $HOME/.config/procs
 
- keybase $KEYBASE_SERVICE_ARGS service &
+  # if kbfsfuse process exits with a match then grep will have a 0 exit code
+  procs --config > $TMP/.config/procs/config.toml
+  procs | grep -i kbfsfuse | grep -qv grep
+  KBFSFUSE_NOT_RUNNING=$?
 
- echo 'starting kbfsfuse'
+  if ! (( $KBFSFUSE_NOT_RUNNING == 0 )); then
+   echo 'starting services'
 
- kbfsfuse $KEYBASE_KBFS_ARGS &
+   keybase $KEYBASE_SERVICE_ARGS service &
 
- echo 'waiting'
+   echo 'starting kbfsfuse'
 
- keybase ctl wait --include-kbfs
-fi
+   kbfsfuse $KEYBASE_KBFS_ARGS &
 
-echo 'baz'
+   echo 'waiting'
 
-keybase status | grep -i 'logged in:' | grep -iq 'no'
-# if logged in then finding 'no' will have a 0 exit code
-LOGGED_IN=$?
-if (( $LOGGED_IN == 0 )) ; then
- echo 'logging in'
- keybase --no-auto-fork --no-debug oneshot
-fi
+   keybase ctl wait --include-kbfs
 
-# @todo - increase the parallelization in xargs
-# would speed things up for many files but needs better output logic
-# specifically, parallel output to a single file interleaves each line which is
-# very bad obviously
-echo 'reading fs'
-keybase fs ls -1 -a --rec $HIVE_KEYBASE_PATH | grep .json | xargs -n 1 -P 1 -I "{}" keybase fs read $HIVE_KEYBASE_PATH/{} > $TMP/items.json
+   echo 'logging in'
+   keybase --no-auto-fork --no-debug oneshot
+  fi
 
-echo 'catting result'
-cat $TMP/items.json
-cat $TMP/items.json | jq -n '.items |= [inputs]'
+  export outdir="$TMP/reads/$REQUEST_ID"
+  mkdir -p $outdir
+  # read up to 20 files in parallel
+  keybase fs ls -1 -a --rec $HIVE_KEYBASE_PATH | grep .json | xargs -n 1 -P 5 -I "{}" bash -c 'keybase fs read $HIVE_KEYBASE_PATH/{} > $outdir/$( cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 ).json'
 
-echo 'fin'
+  # https://github.com/stedolan/jq/issues/744
+  jq --slurp '.' $outdir/*.json > $outdir/items.json
 
-date +%s
+  # Send the response
+  curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response" -s -d @$outdir/items.json
 
-curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response"  -d "z"
+  rm -rf $outdir
+done
